# 			CONFIG FILE
tools:
    privateMessage: true
    keepXp: true
    keepInventory: 'yes'
    showDamage: true
    rider:
        Animal: false
        Player: false
commands:
    CommandOi: true
    CommandHome: true
    CommandMute: true
    CommandCreative: true
    CommandSurvival: true
    CommandAdventure: true
    CommandSpectator: true
    CommandShot: true
    CommandDay: true
    CommandNight: true
    CommandSend: true
    CommandTpa: true
TabList:
  Header: '&3Survival &21.0V\n &9 ------------------------'
  Footer: '&9--------------------\n &3Development By Pedrxd'
settings:
    timeoutSend: 60
