main: pedrxd.survival.Manager
name: Survival
version: 1.1V
author: Pedro Ruiz
commands:
    mute:
        usage: /mute [<player>]
        description: mute some player
    oi:
        usage: /oi <player>
        description: open the inventory of a player
    home:
        usage: /home, /home set
        description: Home
    econfig:
        usage: /econfig
        description: Open the config
    creative:
        usage: /creative [<player>]
        description: Set on creative
    survival:
        usage: /survival [<player>]
        description: Set on survival
    adventure:
        usage: /adventure [<player>]
        description: Set on adventure
    spec:
        usage: /spec [<player>]
        description: Set on spectator
    shot:
        usage: /shot [<player>]
        description: Shot a player to the sky
    slap:
        usage: /slap [<player>]
        description: Shot a player to the sky
    night:
        usage: /night [<world>]
        description: Set the world at night time
    day:
        usage: /day [<world>]
        description: Set the world at day time
    send:
        usage: /send <player>
        description: Send a item to a player.
    accept:
        usage: /accept
        description: Accept a petition
    denny:
        usage: /denny
        description: Denny a petition
